### ISSUE TITLE
Need help : how to use your bundle ?

### ISSUE THREAD

**Issue by rpac-tump** [apinnecke/OAuthBundle#2]
I use your bundle for scoop.it. 
In my controller i create the service
$scoopItService = $this->container->get('apinnecke_oauth.service.scoopit');
When i try 
$result = json_decode($scoopItService->request('profile?shortName=myshortname-xx'), true);
I have this error
**Failed to request resource.**
'HTTP/1.1 401 Unauthorized'
 'Server: nginx'
 'Date: Wed, 25 Jan 2017 13:47:04 GMT'
 'Content-Type: application/x-www-form-urlencoded;charset=UTF-8'
 'Content-Length: 28' 
 'Connection: close'
 'WWW-Authenticate: OAuth realm="scoop.it", oauth_problem="token_rejected"'
Could you please help because i didn't find any information/tutorial to achieve this ? 
Thank you.

**Comment by aklinkert** [comment]
Hey hey,

have you been through the token retrieval before the request is executed? --> As the error says `token_rejected` there's definitely sth. funky with your token. Did you request one?

This Bundle is just a wrapper around the `Lusitanian/PHPoAuthLib` library and hasn't been updated for some time. Here is an example of how to use the plain service from `Lusitanian/PHPoAuthLib`: 
https://github.com/Lusitanian/PHPoAuthLib/blob/master/examples/scoopit.php

**Comment by rpac-tump** [comment]
No i didn't retrieve the token before the execution of the request, how can i do that in a symfony way (controller) because i had a look in the scoopit example but it's not code in sf way. thank you

**Comment by rpac-tump** [comment]
To be more clear, i only want to display scoop.it topics et curated article on the website. I try `profile?shortName=myshortname` just to test.
I try :

```php
$scoopItService = $this->container->get('apinnecke_oauth.service.scoopit');
$token = $scoopItService->requestRequestToken();
$url = $scoopItService->getAuthorizationUri(array('oauth_token' => $token->getRequestToken()));
$response = new Response();
$response->setStatusCode(200);
$response->headers->set('Location', 'url=' . $url);
$response->send();
$result = json_decode($scoopItService->request('profile?shortName=myshortname), true);
```
this return the same oauth_problem="token_rejected"'...

**Comment by aklinkert** [comment]
Please add code blocks to your posts when adding code, that makes reading a lot easier. Thanks.

Are you sure you know how OAuth works and how the OAuth Token Cycle works? OAuth isn't meant for _you_ to request data from _your_ Scoop.it account to display them on your website but to load the data of your *users* from *their* scoop.IT accounts. Your user signs in by OAuth (which includes request cycles to the scoop.IT API), then you get an access token and token secret back which you need to store. You're using them to authenticate yourself at the scoop.it API afterwards to load the actual data. Does that make things more clear?

The Login bundle I was using is https://github.com/hwi/HWIOAuthBundle. To load your own data from the scoop.it API, use static API tokens.

**Comment by rpac-tump** [comment]
You're right about OAuth for signing users. but if you look at the sdk given by scoop.it https://github.com/vdemay/Scoopit-PHP, they used an OAut for the example that interessed me : https://github.com/vdemay/Scoopit-PHP/tree/master/examples/curatedTopicFromUser

**Comment by aklinkert** [comment]
Yah, for sure. Reading over http://www.scoop.it/dev/api/1/intro makes pretty clear, that the API is for accessing the data of a user of yours. Have you tried running the linked example?

**Comment by rpac-tump** [comment]
Sorry which one ? HWIOAuthBundle ?

**Comment by aklinkert** [comment]
This one: https://github.com/vdemay/Scoopit-PHP/tree/master/examples/curatedTopicFromUser

**Comment by rpac-tump** [comment]
yes i did run this one with success but can't integrate it in symfony...

**Comment by aklinkert** [comment]
Huh? I'm pretty surprised it did what you expected ... I'd assume that the `PHPoAuthLib` is doing something funky with the consumer token and secret then. Have you set the client_id and client_secret for scoop.it within your config.yaml like described here? https://github.com/apinnecke/OAuthBundle#configuration

If that's the case you should start debugging the code and see how `PHPoAuthLib` is handling the unavailability of user details.

Maybe this one helps ya: I've written myself a wrapper around the base oAuth request to fill the token store before requesting. OAuthToken is just a DTO holding the key and secret for a specific user:
```php
<?php

namespace BusyGifts\OAuthBundle\Request;

use BusyGifts\OAuthBundle\Exception\ApiRequestFailedException;
use BusyGifts\OAuthBundle\Model\OauthToken;
use OAuth\Common\Service\AbstractService;
use OAuth\Common\Storage\TokenStorageInterface;
use OAuth\OAuth1\Token\StdOAuth1Token;

abstract class BaseOAuth1Request
{
    /**
     * @var AbstractService
     */
    protected $service;

    /**
     * @var TokenStorageInterface
     */
    protected $storage;

    /**
     * @param AbstractService $service
     * @param TokenStorageInterface $storage
     */
    public function __construct(AbstractService $service, TokenStorageInterface $storage)
    {
        $this->service = $service;
        $this->storage = $storage;
    }

    /**
     * @param OauthToken $token
     * @param string $url
     * @return array
     */
    protected function executeRequest(OauthToken $token, $url)
    {
        $oauth1Token = new StdOAuth1Token();
        $oauth1Token->setAccessToken($token->getToken());
        $oauth1Token->setAccessTokenSecret($token->getTokenSecret());
        $this->storage->storeAccessToken($this->service->service(), $oauth1Token);

        $response = $this->service->request($url);

        try {
            $response = json_decode($response, true);
        } catch (\Exception $e) {
            throw new ApiRequestFailedException('Error during parse of received contacts of api: ' . json_last_error_msg(), 0, $e);
        }

        return $response;
    }
}
```

**Comment by rpac-tump** [comment]
Yes i configure the bundle as you told. Thank you for your code. I would like to replicate this part of code in scoopit example from PHPoAuthLib but without the neccesary interaction with link (inside the else), in my controller :

```php
if (!empty($_GET['oauth_token'])) {
    $token = $storage->retrieveAccessToken('ScoopIt');

    // This was a callback request from ScoopIt, get the token
    $scoopItService->requestAccessToken(
        $_GET['oauth_token'],
        $_GET['oauth_verifier'],
        $token->getRequestTokenSecret()
    );

    // Send a request now that we have access token
    $result = json_decode($scoopItService->request('profile'));

    echo 'result: <pre>' . print_r($result, true) . '</pre>';

} elseif (!empty($_GET['go']) && $_GET['go'] === 'go') {
    // extra request needed for oauth1 to request a request token :-)
    $token = $scoopItService->requestRequestToken();

    $url = $scoopItService->getAuthorizationUri(array('oauth_token' => $token->getRequestToken()));
    header('Location: ' . $url);
} else {
    $url = $currentUri->getRelativeUri() . '?go=go';
    echo "<a href='$url'>Login with ScoopIt!</a>";
}
```

**Comment by aklinkert** [comment]
How do you want to execute the request without having logged in? Do you already have the data from `$_GET['oauth_token']`? You will need them to authenticate against the scoop.it API. And doing that login is *NOT* provided by this Bundle and the underlying library. This is just for executing requests.

Assuming you have retrieved the token and verifier the code would be as follows:
```php
$oauth1Token = new StdOAuth1Token();
$oauth1Token->setAccessToken($_GET['oauth_token']);
$oauth1Token->setAccessTokenSecret($_GET['oauth_verifier']);
$this->storage->storeAccessToken('ScoopIt', $oauth1Token);
$result = json_decode($scoopItService->request('profile'));
die($result);
```

**Comment by rpac-tump** [comment]
the token that i have is the one from $token = $scoopItService->requestRequestToken();.
A var_dump give me this 
`object(OAuth\OAuth1\Token\StdOAuth1Token)[822]
  protected 'requestToken' => string '47nT4skNkAUDvSrELExg-etc' (length=43)
  protected 'requestTokenSecret' => string 'SKyL6XkTz6MWZYsXT6UXhMjQ3EONkH2HS@etc' (length=50)
  protected 'accessTokenSecret' => string 'SKyL6XkTz6MWZYsXT6UXhMjQ3EONkH2HS@etc' (length=50)
  protected 'accessToken' => string '47nT4skNkAUDvSrELExg-etc' (length=43)
  protected 'refreshToken' => null
  protected 'endOfLife' => int -9002
  protected 'extraParams' => 
    array (size=1)
      'oauth_callback_confirmed' => string 'true' (length=4)`

**Comment by rpac-tump** [comment]
and yes i don't have the oauth_token and the oauth_verifier. I shoull have these after calling $url, i imagine :
`
$url = $scoopItService->getAuthorizationUri(array('oauth_token' => $token->getRequestToken()));
header('Location: ' . $url);
`
 But how can i do in symfony way.
I try :
`$response = new Response();
$response->setStatusCode(200);
$response->headers->set('Location', 'url=' . $url);
$response->send();`
but after that, i'm stuck

**Comment by aklinkert** [comment]
Dude, this requestToken is for the authentication process, not to request data from the api.

To send a Response in Symfony have a look here: https://symfony.com/doc/current/controller.html or just use https://symfony.com/doc/current/controller.html#redirecting .

The easiest way for you to achieve your goal would be to use https://github.com/hwi/HWIOAuthBundle for authentication.

---

I'm gonna close this one since it's not an issue at all but more of a lack of base knowledge. Please read the docs of Symfony and try to integrate the HWIOAuthBundle for authentication.

**Comment by rpac-tump** [comment]
thank you for your time.
